import { pastDays, type DemoState, type UserProfile } from './types';

export const DEFAULT_USERS: UserProfile[] = [
  {
    id: 'user-chandu',
    username: 'chandu',
    display_name: 'Chandu',
    wallet_address: '0x0CD9489AfcCc42B0ccFD463E53D3C9bb24c9A3f3',
    bio: 'Building Dracarys on Monad Testnet 🔥',
    avatar_color: 'purple',
    initials: 'CK',
    streak_count: 5,
    total_earned_mon: 0.25,
  },
  {
    id: 'user-abubaker',
    username: 'abubaker',
    display_name: 'Abubaker',
    wallet_address: '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
    bio: 'Building a better me every day',
    avatar_color: 'peach',
    initials: 'AB',
    streak_count: 8,
    total_earned_mon: 0.40,
  },
  {
    id: 'user-abdul',
    username: 'abdul',
    display_name: 'Abdul',
    wallet_address: '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC',
    bio: 'Consistency is my superpower',
    avatar_color: 'mint',
    initials: 'AJ',
    streak_count: 6,
    total_earned_mon: 0.30,
  },
];

export function initialState(): DemoState {
  return {
    sound: true,
    joinedCodes: [],
    user: DEFAULT_USERS[0],
    challenges: [
      {
        id: 'gym',
        title: 'Show up. Get stronger.',
        description: '30 minutes of movement, every day.',
        kind: 'fitness',
        duration: 21,
        dailyStake: '0.1',
        completed: 5,
        checkInDates: pastDays(5),
        inviteCode: 'DRA-GYM21',
        members: 4,
        earnedUsd: 1.2,
        lockedUsd: 5,
      },
      {
        id: 'read',
        title: 'One more chapter.',
        description: 'Read 20 pages. Feed your mind.',
        kind: 'reading',
        duration: 14,
        dailyStake: '0.05',
        completed: 3,
        checkInDates: pastDays(3),
        inviteCode: 'DRA-READ14',
        members: 3,
      },
      {
        id: 'breathe',
        title: 'A little more present.',
        description: '10 minutes. Just you and your breath.',
        kind: 'mindfulness',
        duration: 7,
        dailyStake: '0.02',
        completed: 2,
        checkInDates: pastDays(2),
        inviteCode: 'DRA-CALM7',
        members: 2,
      },
    ],
    approvals: [
      {
        id: 'maya',
        name: 'Maya Chen',
        initials: 'MC',
        color: 'peach',
        challenge: 'Morning movement',
        kind: 'fitness',
        streak: 8,
        note: 'Leg day, done! 35 minutes of strength training before work. Feeling stronger already.',
        approved: false,
      },
      {
        id: 'alex',
        name: 'Alex Rivera',
        initials: 'AR',
        color: 'lilac',
        challenge: 'Read 20 pages',
        kind: 'reading',
        streak: 4,
        note: 'Pages 42–62 of Atomic Habits. Today’s takeaway: make the good habit the easy choice.',
        approved: false,
      },
      {
        id: 'sam',
        name: 'Sam Wilson',
        initials: 'SW',
        color: 'mint',
        challenge: 'Mindful mornings',
        kind: 'mindfulness',
        streak: 6,
        note: 'Ten quiet minutes with my phone on airplane mode. Best way to start the day.',
        approved: false,
      },
    ],
  };
}
