import { pastDays, type DemoState } from './types';
export function initialState(): DemoState {
  return {
    sound: true,
    joinedCodes: [],
    challenges: [
      {
        id: 'gym',
        title: 'Show up. Get stronger.',
        description: '30 minutes of movement, every day.',
        kind: 'fitness',
        duration: 21,
        dailyStake: '0.1',
        completed: 5,
        checkInDates: pastDays(5),
        inviteCode: 'STR-GYM21',
        members: 4,
        earnedUsd: 1.2,
        lockedUsd: 5,
      },
      {
        id: 'read',
        title: 'One more chapter.',
        description: 'Read 20 pages. Feed your mind.',
        kind: 'reading',
        duration: 14,
        dailyStake: '0.05',
        completed: 3,
        checkInDates: pastDays(3),
        inviteCode: 'STR-READ14',
        members: 3,
      },
      {
        id: 'breathe',
        title: 'A little more present.',
        description: '10 minutes. Just you and your breath.',
        kind: 'mindfulness',
        duration: 7,
        dailyStake: '0.02',
        completed: 2,
        checkInDates: pastDays(2),
        inviteCode: 'STR-CALM7',
        members: 2,
      },
    ],
    approvals: [
      {
        id: 'maya',
        name: 'Maya Chen',
        initials: 'MC',
        color: 'peach',
        challenge: 'Morning movement',
        kind: 'fitness',
        streak: 8,
        note: 'Leg day, done! 35 minutes of strength training before work. Feeling stronger already.',
        approved: false,
      },
      {
        id: 'alex',
        name: 'Alex Rivera',
        initials: 'AR',
        color: 'lilac',
        challenge: 'Read 20 pages',
        kind: 'reading',
        streak: 4,
        note: 'Pages 42–62 of Atomic Habits. Today’s takeaway: make the good habit the easy choice.',
        approved: false,
      },
      {
        id: 'sam',
        name: 'Sam Wilson',
        initials: 'SW',
        color: 'mint',
        challenge: 'Mindful mornings',
        kind: 'mindfulness',
        streak: 6,
        note: 'Ten quiet minutes with my phone on airplane mode. Best way to start the day.',
        approved: false,
      },
    ],
  };
}
